[package]
name = "create-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
inquire = { version = "0.7.5", features = ["editor"] }
regex = "1.11.1"
serde = "1.0.215"
serde_json = "1.0.133"
