{
  lib,
  hostName,
  system,
  inputs,
  pkgs,
  ...
}: let
in {
  home-manager.users.bean = {
    wayland.windowManager.hyprland = {
      enable = true;
      package = pkgs.hyprland;
      systemd.variables = ["--all"];
      extraConfig = ''
        bind = SUPER,M,submap,passthru
        submap = passthru
        bind = SUPER,ESCAPE,submap,reset
        submap = reset
      '';
      settings = {
        autogenerated = 0;
        monitor = [
          "HDMI-A-1,1920x1080,0x0,1"
          "DVI-D-1,1920x1080,1920x0,1"
          "eDP-1,2256x1504,0x0,1,bitdepth,10"
          ",highres,auto,1"
        ];
        general = {
          border_size = 2;
          resize_on_border = true;
          "col.active_border" = "rgb(ff0000) rgb(ff9a00) rgb(d0de21) rgb(4fdc4a) rgb(3fdad8) rgb(2fc9e2) rgb(1c7fee) rgb(5f15f2) rgb(ba0cf8) rgb(fb07d9) 45deg";
        };
        decoration = {
          rounding = 10;
        };
        input = {
          numlock_by_default = true;
          touchpad = {
            natural_scroll = true;
          };
        };
        gestures = {
          workspace_swipe = true;
        };
        xwayland = {
          force_zero_scaling = true;
        };
        # debug = {
        #   disable_logs = false;
        # };
        misc = {
          enable_swallow = true;
          # swallow_regex = "^(foot)$";
          disable_hyprland_logo = true;
          disable_splash_rendering = true;
          focus_on_activate = true;
          mouse_move_enables_dpms = true;
          key_press_enables_dpms = true;
        };
        env = [
          "TERMINAL,foot"
        ];
        windowrulev2 = [
          "workspace 1 silent,class:(.*)vesktop(.*),title:(.*)[Vv]esktop(.*)"
          "idleinhibit fullscreen,class:(.*),title:(.*)"
        ];
        submap = "reset";
        bind = let
          openTerminal = "foot";
          forEachWorkspace = {
            mod,
            dispatch,
          }:
            builtins.genList (i: let
              num = builtins.toString i;
            in "${mod},${num},${dispatch},${
              if num == "0"
              then "10"
              else num
            }")
            10;
        in
          [
            "SUPER,M,submap,passthru"
            "SUPER,Q,exec,firefox-devedition"
            "SUPER,Z,exec,systemctl suspend"
            ",XF86AudioMedia,exec,${openTerminal}"
            "SUPER,T,exec,${openTerminal}"
            "SUPER ALT CTRL SHIFT,L,exec,xdg-open https://linkedin.com"
            "SUPER,C,killactive,"
            "SUPER SHIFT,D,exec,code"
            "SUPER,P,pseudo,"
            "SUPER,R,togglefloating,"
            "SUPER,F,fullscreen,1"
            "SUPER SHIFT,F,fullscreen,0"
            "SUPER,J,togglesplit,"
            "SUPER,left,movefocus,l"
            "SUPER,right,movefocus,r"
            "SUPER,up,movefocus,u"
            "SUPER,down,movefocus,d"
            "SUPER,G,togglegroup"
            "SUPER SHIFT,G,lockactivegroup, toggle"
            "SUPER,TAB,changegroupactive"
            "SUPER SHIFT,TAB,changegroupactive,b"
            ",XF86RFKill,exec,rfkill toggle wifi"
          ]
          ++ forEachWorkspace {
            mod = "SUPER";
            dispatch = "workspace";
          }
          ++ forEachWorkspace {
            mod = "SUPER SHIFT";
            dispatch = "movetoworkspace";
          };
        bindm = [
          "SUPER,mouse:272,movewindow"
          "SUPER,mouse:273,resizewindow"
        ];
      };
    };
  };
}
